### ISSUE TITLE
cannot build custom database with mmpDBbuilder.py

### ISSUE THREAD

**Issue by jagos01** [microbiome-gastro-UMG/MeTaPONT#5]
Hello Tim,
Sorry for opening a new issue, I could not figure out how to reopen my closed issue (https://github.com/microbiome-gastro-UMG/MeTaPONT/issues/4#issue-1214445723).

I have re-cloned the repo and built the docker image.  I copied cdbfasta and cdbyank into the MeTsPONT directory and then executed the following command to build my custom database. 

nohup python3 mmpDBbuilder.py /home/data0/metapont_db/conversionTable.txt /home/DRDC/data0/metapont_db/centrifuge-abv-univec-bp.fasta.cidx 10

As before, only an empty folder was created (fastaTaxID) and the contents of nohup.out are as follows:

A usable Database will be build from 
 conversion table 	 /home/data0/metapont_db/conversionTable.txt
 with fasta index 	 /home/data0/metapont_db/centrifuge-abv-univec-bp.fasta.cidx

We will start at taxID 0 and use 10 subprocesses.
building DFs took  0.08470541599672288  s
processing 19372  taxids took  0.12189851500443183

Am I using the mmpDBbuilder script correctly?
Thanks for your help,
Scott

**Comment by tim488** [comment]
Hey Scott, 
sorry for the delay. I think I fixed the issue. It works now on my machine. If this doesn't work for you feel free to follow up!
Cheers, Tim

**Comment by jagos01** [comment]
Hello Tim,
I have successfully built my database.  
Thank you for the fix.
Scott
